apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockmanager
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
        - name: stockmanager
          image: shreelakshmispsl/stockmanager:latest
          ports:
            - containerPort: 8030
          livenessProbe:
            httpGet:
              path: /health
              port: 8030
            initialDelaySeconds: 30
            timeoutSeconds: 1
